on:
  workflow_call:
    inputs:
      path-filter:
        description: 'Path containing the source code.'
        required: true
        type: string
      file-ignore:
        description: 'Files to be ignored.'
        default: ''
        required: false
        type: string

jobs:
  updater:
    runs-on: ubuntu-latest

    steps:

      - name: ğŸ“¦ Checkout caller
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Checkout eureka-scraper
        uses: actions/checkout@v3
        with:
          repository: leowajda/eureka-scraper
          path: eureka-scraper

      - name: ğŸ¦º Retrieve changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          separator: " "
          files_ignore: |
            ${{ inputs.file-ignore }}
          files: |
            ${{ inputs.path-filter }}

      - name: ğŸ“¦ï¸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: ğŸ“Œ Install pip dependencies
        run: pip install -r .github/workflows/requirements.txt

      - name: ğŸš€ Run script
        run: python eureka-scraper/.github/workflows/script.py ${{ github.event.repository.url }} ${{ steps.changed-files.outputs.all_changed_files }}

      - name: âœ¨ Auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":octocat: Update /docs and README.md"